Name: hello prohub_project

on:

  push:

    branches: [ "main" ]
    
  pull_request:
  
    branches: [ "main" ]
    
  workflow_dispatch:
  
jobs:

  build:
   run-on: ubuntu-latest

  stepes:

    uses: actions/chechout@v4

    name: Run a one-line script
        run: echo Hello, world!

           - name: Run a multi-line script
        run: |
          echo: "prohub_project"
    
